name: iOS Test

on: [push]

jobs:
  build_and_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: Testing
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: "test"
